version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: pip install poetry
      - run: poetry install
      - run: poetry build
      - run: poetry run pytest ./watson_jira_next
workflows:
  pull_request:
    jobs:
      - test
