version: 2.1
orbs:
  poetry: frameio/poetry@0.23.0
workflows:
  ci:
    jobs:
      - poetry/build
      - poetry/shell:
          args: pytest ./watson_jira_next
          requires:
            - poetry/build
