#jira:
  #server: yourproject.atlassian.net
  #personalAccessToken: <<PAT>>
  #email: youremail@example.com
  #apiToken: <<API token
  #cookie: atlassian.xsrf.token=BEHZ-5GE9-RXNS-7J78_bfa98881ae96448d36fdaa94f2b3ac6b8f205885_lout; JSESSIONID=51D8547A4C356A8355F8FDAF7CC97D51
#mappings:
  #- name: sprint
    #type: issue_specified_in_tag
  #- name: vacation
    #type: single_issue
    #issue: JIRA-1
  #- name: maintenance
    #type: issue_per_project
    #projects:
      #project1: JIRA-2
      #project2: JIRA-3
