categories:
  - name: sprint
    description: 'Activities performed in scope of sprint related to planned issues.'
    type: issue_specified_in_tag
  - name: vacation
    description: 'Vacation'
    type: single_issue
    issue: JIRA-1
  - name: other
    description: 'Generic activities not related to any task in the current sprint.'
    type: issue_per_project
    projects:
      project1: JIRA-2
      project2: JIRA-3
